# Based on the video from https://github.com/avinashsingh93/Finding-Lane-Lines/blob/master/test_videos/solidWhiteRight.mp4
# and https://github.com/avinashsingh93/Finding-Lane-Lines/blob/master/test_videos/solidYellowLeft.mp4
# Mask coordinates depend on camera position

# Line detection related config
line_detection:
  mask_points:
      - [60, 540]
      - [480, 300]
      - [960, 540]

  # Canny positions
  canny:
    low_threshold: 100
    high_threshold: 200

  # HoughLinesP parameters
  hough_lines:
    rho: 5
    theta: 0.0523333
    threshold: 160
    min_line_length: 40
    max_line_gap: 25

  # GaussianBlur size
  blur_size:
    height: 1
    width: 1

  # Slope intercept used for drawing the lines
  line_slope: 0.6

  # Gamma cofficient used for farkening. 1.0 for no change
  gamma_cof: 0.5

  # Enable further checks like darkening image, masking to only to yellow and white spectre
  additional_checks: false

  # Used for camera calibration for getting undistorted images
  calibration_path: ""
  chess_x: 9
  chess_y: 6

# Object detection related config
object_detection:
  model: "ssd_mobilenet_v2_coco_2018_03_29.pb"
  config: "ssd_mobilenet_v2_coco_2018_03_29.pbtxt"
  mean: [0, 0, 0]
  scale: 1.0
  width: 300
  height: 300
  rgb: true
  classes: "object_detection_classes_coco.txt"
  # Confidence threshold
  cnf_threshold: 0.5
  # Non-maximum suppression threshold
  nms_threshold: 0.4