# Based on https://www.youtube.com/watch?v=fkps18H3SXY 720p
# Not fully optimized

# Line detection related config
line_detection:
  # Mask coordinates depend on camera position
  mask_points:
      - [200, 720]
      - [670, 360]
      - [1110, 720]

  # Canny positions
  canny:
    low_threshold: 50
    high_threshold: 100

  # HoughLinesP parameters
  hough_lines:
    rho: 2
    theta: 0.0174444
    threshold: 100
    min_line_length: 20
    max_line_gap: 150

  # GaussianBlur size
  blur_size:
    height: 5
    width: 5

  # Slope intercept used for drawing the lines
  line_slope: 0.7

  # Gamma cofficient used for farkening. 1.0 for no change
  gamma_cof: 0.5

  # Enable further checks like darkening image, masking to only to yellow and white spectre
  additional_checks: false

# Object detection related config
object_detection:
  model: "ssd_mobilenet_v2_coco_2018_03_29.pb"
  config: "ssd_mobilenet_v2_coco_2018_03_29.pbtxt"
  mean: [0, 0, 0]
  scale: 1.0
  width: 300
  height: 300
  rgb: true
  classes: "object_detection_classes_coco.txt"
  # Confidence threshold
  cnf_threshold: 0.5
  # Non-maximum suppression threshold
  nms_threshold: 0.4